name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r frontend/requirements.txt
        pip install black flake8 mypy
    
    - name: Run Black (Code Formatting)
      run: |
        black --check --diff backend/ frontend/ tests/
    
    - name: Run Flake8 (Linting)
      run: |
        flake8 backend/ frontend/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend/ frontend/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics
    
    - name: Run MyPy (Type Checking)
      run: |
        mypy backend/ --ignore-missing-imports
        mypy frontend/ --ignore-missing-imports
